baseEmmaUrl: http://emmauat1.msrb.org/
baseDataportUrl: http://dataportuat1.msrb.org/
userId: amansoor1
password: MSRB*login1
email: abyss@msrb.org
myEmma:
    userId: sjones@msrb.org
    password: Courtney1
